# -- SOLVED ISSUE --
# https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend

# -- LAUNCH --
exec-once = kime # for input method
# exec-once = fcitx5 # for input method
exec-once = swayidle -w timeout 1200 'swaylock; hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' timeout 1800 'systemctl suspend' # lock & turn off monitor after 20 mins, suspend after 30 mins // install swayidle

# -- ENV -- 
env = WLR_NO_HARDWARE_CURSORS, 1 # prevent invisible cursor

env = XMODIFIERS, @im=fcitx
env = GTK_IM_MODULE, fcitx
env = QT_IM_MODULE, fcitx
# -- INPUT --
input {
  # check /usr/share/X11/xkb/rules/base.lst
  kb_options = ctrl:swapcaps, korean:ralt_hangul
}

# -- ANIMATIONS --
animations {
  enabled = no
}

# -- KEYBINDINGS -- 
# Application shortcuts
unbind = $mainMod, F
unbind = $mainMod, C
unbind = $mainMod, T
unbind = $mainMod, B
unbind = $mainMod, A
bind = $mainMod, T, exec, ghostty
bind = $mainMod, B, exec, brave --password-store=archlinux-keyring
bind = $mainMod, F, exec, firefox
bind = ALT, SPACE, exec, pkill -x rofi || $scrPath/rofilaunch.sh d # launch desktop applications

# Switch workspaces with mainMod + [0-9]
bind = CTRL, 1, workspace, 1
bind = CTRL, 2, workspace, 2
bind = CTRL, 3, workspace, 3
bind = CTRL, 4, workspace, 4
bind = CTRL, 5, workspace, 5
bind = CTRL, 6, workspace, 6
bind = CTRL, 7, workspace, 7
bind = CTRL, 8, workspace, 8
bind = CTRL, 9, workspace, 9
bind = CTRL, 0, workspace, 10

# Move focus with mainMod + arrow keys
unbind = $mainMod, H
unbind = $mainMod, L
unbind = $mainMod, K
unbind = $mainMod, J
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Move active window around current workspace with mainMod + SHIFT + CTRL [←→↑↓]
bind = CONTROLALT, H, movewindow, l
bind = CONTROLALT, L, movewindow, r
bind = CONTROLALT, K, movewindow, u
bind = CONTROLALT, J, movewindow, d

# Fullscreen mode
unbind = ALT, return
bind = CONTROLALT, return, fullscreen
